name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.x

        # Build
        - name: Build
          run: dotnet build src/Set.BlazorClient/Set.BlazorClient.csproj

        # Run tests
        - name: Run tests
          run: dotnet test test/Set.xTest/Set.UnitTests.csproj


        # Generate the website
        - name: Publish
          run: dotnet publish src/Set.BlazorClient/Set.BlazorClient.csproj --configuration Release --output build
          
        # Rewrite base href
        - name: Rewrite base href
          uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
          with:
            html_path: ${{ env.PUBLISH_DIR }}/index.html
            base_href: /setgame/

        - name: Deploy to Github Pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
            BASE_BRANCH: master # The branch the action should deploy from.
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: build/wwwroot # The folder the action should deploy.
            SINGLE_COMMIT: true